dist: trusty
language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
before_script:
- npm install -g snyk@1.360.0
- snyk -v
- snyk auth $SNYK_TOKEN
script:
- sbt "project core" clean startDynamodbLocal test dynamodbLocalTestCleanup stopDynamodbLocal
- sbt "project transformer" clean startDynamodbLocal test dynamodbLocalTestCleanup stopDynamodbLocal
- sbt "project loader" clean startDynamodbLocal test dynamodbLocalTestCleanup stopDynamodbLocal
before_deploy:
- pip install --user release-manager==0.4.1
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
after_deploy:
- snyk monitor --project-name=snowplow-snowflake-loader
env:
  global:
  - secure: Xkj+6nQQm43Y3G5D2p9QilPQmYy8V25KqqYIMjXxH16l5UEvHz4SMl8+mNJ2pSsfgxwGKOPE0uZf34H9m343CCmJX0npzH4o5SudOuu+HJAYQRd8DDjkd85V2wRgElSXx5bo3741T2PxYy3oIIpSECEg3IaWeMYXho8H2hgWFj9U7L8rZegrIXyqodjjzwrg8Eusw2LjAK4C5BvAnc7e4ENPpbAP/61f0xBupceu0Y39CSb/CEtnDUKIotyZ0p0T8+XjYW09s35/qgjVFEJ1/wDkMDgIqo+DQ4hKh0v/yIqg5lEmJjLxEvokwOAgVu3o9NB5g3v60ajUdwA10XeFU8uc5BvIEDXEjEhwaqQK0iNuL5CoQkcVsszAmVLd8G9NRFnI1Vs825nFf6j3Uw3S6EDkwdVfkCtJEOznID+Bq3cTx4iLrGeTj9gaChNHwa8UynQlCs2OzY6eZw8DQf1wP2d4R1CUS9Uexsn52qnfr9rsmolvOkTeu6wSzomV7whjSxvFnxEVlsEkwj0x94JjoSMwo9eN9AXJYPKBlgvuJUWzCIAGabriGbAANGdrK8d9fWqNIr4LyIL5UavtFeyYuDhPjLxeMHGZ3Bhv4reQb0YFgFbd4NIzSL6p7ZwhQwBZdjkDsZfnKv2heHkw6j0X7w6REss3doWwmXrS7a1CEMk=
  - secure: GVgq2/lBvF8kpZ8f5AShFFDNQg3Re10EDe02qQmuqBRNiUk5GRCZ0oivUmLrfn/7AxN95YGoV60QwsQzdEy3DcQT8Q2KnJqa5LGwO0HVm+NSbdJ/G9uqLO+TINL0XOZ267rRAGsLk52edAKZRafk5WwAtO81dnuNyw2dUPO+0PVb+BcnWk554m0AXw0UNEoorVwPJiwyjMm59f4uDts0yb2M+tGrkuKloM6N1iLFSCPwbP+uVg/lwJIi3HoX76j9vpxo6odELSQpbYeJBSBGEi3KaZPPID1L50LUUZsc0TsgRlKUNMc3hern66JncD6NJhnoyGLXPELli0+Cdu2Qz7+7fi7QcF1IUgqJXKfEwYf8bFfAOUcVL+woYSUszPZsVsOWtRhbF999B8xXVgyhWs5nL7sqmiQM90U0GbVpudqM2IhMplFz4UhIHMD5kL6x9RyUXJiBXJpMT1Xq3VIt9uZl8v2iyxK2Vbzi/fP78gIQe4Ub/iZ8faqIY5DCg7mc7ojr4JjDPgsv6v9BYzdR91En05kOm2I8HlmxwXa+2OMI203ie05OSnATHaJ0fYmE7tzGlg1hNiBITzRknh+Ud2vfLv0zN49r/wjF6URaTVtaZiq1Q50Iv0FoQJL5xakMWBkcokhyCzeYpPaIri4DuF1iF7LtK1DBGT9QagHB9rs=
  - secure: CLFhMaMKhKCV+gyMJ/QiFyex+pug2u/nA0S+N/VxTx7nrHT+0/E18tD5RaM0x4ajcjMpsHHI0tMzsfa8LDpWO1wcaJ+j0kM/vULXAsV0vyVtIX2Y8trAt1s2CuTHYWxeqoC9FjLzQ5dnp9g8FKpeJaNOINj1epjAIlJ/iTNp1aZqYapefFt7s+6EElovdYjsD95VXvC5OudBGthDZNVGv8a5obcqf5DQ/aSm1hJTpBdEro07oVvsIPHSlqc6POAHNBQNzQnASHGtTXoHSrpSqXlPf4gYhjdERpXmPe+P0CyPXWMuWaEH2CuOcxNCFtZIXK3WyNi/5yuKzUk3AFDjg0pcQ/bqIVbGxZTTtZ9WiSgs4WWgLrQyAVjwEK9KYEq0CCVkdmta7WEHAQ4Q2SASAmcfFPvgGLziItG/MaGmCl8R3nbpQd9MpNjz25gT19RTsJqnkAQ/6J8Tvr3emKXUfd+GbwHyfrptQBcTaQxkxIooyTLaKnbErL15Yqr7UGWQWYrL0HPEPxXKQsOXGPwS/2TZP0kHMrYFVRM8vVF9ceMNCZK3hmFdqMI3ov3nH09Ti0HrkHrPM3GJZkFt6CL3jne4ELdpopDTThv2GLujqmzVuplZ10PKg4ZBnS2I1fbnaVbLtOPBvAGpjG044Rse+5VB1U0MxVDToi2Gj35f0iw=
